FORMAT: 1A
HOST: https://hingastores.herokuapp.com/

# StoreManager

Storemanager is a simple API that allows store owners manage inventory and track sales

## Admin/Store Attendant Log In [/api/v2/auth/login]

### Login a registered user [POST]

Both admins and store attendants can login into their accounts. It takes a JSON
object containing an email and password.

+ Request (application/json)

        {
            "email": "super@admin.com",
            "password": "A123@admin"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/v2/auth/login

    + Body

            {
                "message": "Logged in successfully!",
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDExMjcyNjAsIm5iZiI6MTU0MTEyNzI2MCwianRpIjoiODEyMzQwZWUtMmUyNy00NDIyLWE0NDgtNzZiMDZhNTZkNDEwIiwiZXhwIjoxNTQxMTI4MTYwLCJpZGVudGl0eSI6ImFuZHJld2hpbmdhQHN0b3JlLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.i5uOF6gzH4rWKuywQ3RF5PBZd3eCo_aePyMr0WbVrtw"
            }
            

## Store attendants accounts creation [/api/v2/auth/signup]

### Create a New store attendant account [POST]

Only an admin can create a new store attendant account. It takes a JSON
object containing a name, email, password and a role

+ Request (application/json)

    + Headers
            
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84
    
    + Body
    
            {
                "name": "john henry",
                "email": "john@store.com",
                "password": "W12345@#",
                "role": "normal"
            }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "message": "User created!",
                "user": {
                    "name": "john henry",
                    "email": "john@store.com",
                    "password": "W12345@#",
                    "role": "normal"
                    }
            }
            
            
## Products [/api/v2/products]

### Create a New product [POST]

Only an admin can create a new product. It takes a JSON
object containing a category, name, quantity and price.

+ Request (application/json)
    + Body
    
            {
                "category": "foods",
                "name": "Coffee Mocha",
                "quantity": 6,
                "price": 500
            }
        
    + Headers
    
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84
        

+ Response 201 (application/json)

    + Headers

            Location: /api/v2/products

    + Body

            {
                "message": "Product created successfully",
                "product": {
                    "category": "foods",
                    "date_created": "Fri, 02 Nov 2018 05:56:56 GMT",
                    "name": "Coffee Mocha",
                    "price": "500",
                    "quantity": "66"
                },
                "status": "created"
            }
            
### Fetch all Products [GET]

Both admin and store attendant can view all products

+ Response 200

    + Headers

            Location: /api/v2/products
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84

    + Body

            {
                "message": "Product created successfully",
                "product": {
                    "category": "foods",
                    "date_created": "Fri, 02 Nov 2018 05:56:56 GMT",
                    "name": "Coffee Mocha",
                    "price": "500",
                    "quantity": "66"
                },
                "status": "created"
            }
            
## Single Product [/api/v2/products/{product_id}]

+ Parameters
    + product_id (number) - ID of the question in the form of an integer

### Delete a single product by id [DELETE]

Only an admin/store owner can delete a product.


+ Response 200

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84"

    + Body

            {
                "message": "product has been deleted"
            }

            

### Update a single product by id [PUT]

Only an admin can modify product details


+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84
    + Body
    
            {
                "category": "foods",
                "name": "Chicken",
                "quantity": 230,
                "price": 5000
            }
        

+ Response 201 (application/json)


    + Body

            {
                "Product": {
                    "category": "foods",
                    "date_created": "Fri, 02 Nov 2018 06:06:39 GMT",
                    "id": 2,
                    "name": "Chicken",
                    "price": [
                        "5000"
                    ],
                    "quantity": [
                        "230"
                    ]
                },
                "message": "Updated successfully"
            }
            
### Fetch a single product by id [GET]

Either an admin or a store atendant can view a single product

+ Response 200

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84

    + Body

            {
                "Product": {
                    "category": "foods",
                    "date_created": "Fri, 02 Nov 2018 06:06:13 GMT",
                    "id": 2,
                    "name": "Chicken",
                    "price": 5000,
                    "quantity": 230
                },
                "message": "success"
            }


## Sales [/api/v2/sales]


### Create a New sale record [POST]

Only a store attendant can create a new sale record. It takes a JSON
object containing a product_id and quantity.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84
        
    + Body
    
            {
                "product_id": 1,
                "quantity": 2
            }
        

+ Response 201 (application/json)

    + Headers

            Location: /api/v2/sales

    + Body

            {
                "message": "Sale record created successfully",
                "product": {
                    "date_created": "Fri, 02 Nov 2018 02:33:13 GMT",
                    "name": "MacBook",
                    "price": 153200,
                    "product_id": "1",
                    "quantity": 2,
                    "remaining_q": 28
                },
                "status": "created"
            }
            
### Fetch all sales [GET]

Only a store owner/ admin can view all sales.
        

+ Response 200

    + Headers

            Location: /api/v2/sales
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84

    + Body

            {
                "Sales": [
                    {
                        "date_created": "Wed, 31 Oct 2018 17:16:28 GMT",
                        "id": 1,
                        "name": "Coffee Mocha",
                        "price": 5500,
                        "product_id": 1,
                        "quantity": 11,
                        "remaining_q": 40
                    },
                    {
                        "date_created": "Wed, 31 Oct 2018 18:20:22 GMT",
                        "id": 2,
                        "name": "Coffee Mocha",
                        "price": 5500,
                        "product_id": 1,
                        "quantity": 11,
                        "remaining_q": 40
                    }
                ],
                "message": "success",
                "status": "ok"
            }
            
## Single Sale [/api/v2/sales/{sale_id}]

+ Parameters
    + sale_id (number) - ID of a sale in form of an integer

### Fetch a single sale record [GET]

Only the store owner/admin and the creater of the sale can view the single sale.

+ Response 200

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NDIxMjg2NzgsIm5iZiI6MTU0MjEyODY3OCwianRpIjoiNzNkMDg0NTYtNzE2MS00OWFlLWJkOGEtY2M4YTkyZGZiYTdkIiwiZXhwIjoxNTQyMTI5NTc4LCJpZGVudGl0eSI6InN1cGVyQGFkbWluLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.dRmjiH8SgqAdvs6X0iDQklLd_qN8kMP_iey-xTBlo84

    + Body

            {
                "Sale": {
                    "date_created": "Fri, 02 Nov 2018 08:21:43 GMT",
                    "id": 1,
                    "name": "Chicken",
                    "price": 10000,
                    "product_id": 2,
                    "quantity": 2,
                    "remaining_q": 228
                },
                "message": "success"
            }