FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# storemanager

Storemanager is a simple API that allows store owners manage inventory and track sales

## Users [/api/v2/auth]

### Create a New store attendant account [POST]

An admin can create a new store attendant account. It takes a JSON
object containing a name, email, password and a role

+ Request (application/json)

        {
            "name": "john henry",
            "name": "john@store.com",
            "name": "W12345@#",
            "name": "normal"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "message": "User created!",
                "user": {
                    "name": "john henry",
                    "email": "john@store.com",
                    "password": "W12345@#",
                    "role": "normal"
                    }
            }
            
## Products [/api/v2/products]

### Create a New product [POST]

An admin can create a new product. It takes a JSON
object containing a category, name, quantity and price.

+ Request (application/json)
    
        {
            "category": "foods",
            "name": "Coffee Mocha",
            "quantity": 6,
            "price": 500
        

+ Response 201 (application/json)

    + Headers

            Location: /api/v2/products

    + Body

            {
                "message": "Product created successfully",
                "product": {
                    "category": "foods",
                    "date_created": "Fri, 02 Nov 2018 05:56:56 GMT",
                    "name": "Coffee Mocha",
                    "price": "500",
                    "quantity": "66"
                },
                "status": "created"
            }

## Sales [/api/v2/sales]

### Create a New sale record [POST]

A store attendant can create a new sale record. It takes a JSON
object containing a product_id and quantity.

+ Request (application/json)
    
        {
            "product_id": 1,
            "quantity": 2
        

+ Response 201 (application/json)

    + Headers

            Location: /api/v2/sales

    + Body

            {
                "message": "Sale record created successfully",
                "product": {
                    "date_created": "Fri, 02 Nov 2018 02:33:13 GMT",
                    "name": "MacBook",
                    "price": 153200,
                    "product_id": "1",
                    "quantity": 2,
                    "remaining_q": 28
                },
                "status": "created"
            }